body:
  - type: textBlock
    attributes:
      description: Configure your HTTP Query Forwarder plugin to connect to your custom HTTP server.

  - type: input
    attributes:
      name: server_address
      label: "Server Address:"
      description: "HTTP/HTTPS server address (e.g., http://176.108.244.147)"
      defaultValue: "http://127.0.0.1"

  - type: input
    attributes:
      name: server_port
      label: "Server Port:"
      description: "Server port number"
      defaultValue: "8080"

  - type: input
    attributes:
      name: server_path
      label: "Server Path:"
      description: "Path on the server (e.g., / or /api/search)"
      defaultValue: "/"

  - type: input
    attributes:
      name: query_param_name
      label: "Query Parameter Name:"
      description: "Name of the query parameter (e.g., 'q' results in ?q=...)"
      defaultValue: "q"

  - type: checkbox
    attributes:
      name: url_encode_query
      label: "URL Encode Query"
      description: "Enable URL encoding for the query parameter"
      defaultValue: true

  - type: input
    attributes:
      name: request_timeout
      label: "Request Timeout (seconds):"
      description: "Maximum time to wait for server response"
      defaultValue: "5"

  - type: textarea
    attributes:
      name: custom_url_template
      label: "Custom URL Template:"
      description: "Optional: Use {query} or {encoded_query} for custom URL format"
      defaultValue: ""
